services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: spigot-server-1.20.4
    stdin_open: true
    tty: true
    ports:
      - "9584:25565"
    volumes:
      - ./server:/app/server
    networks:
      - mc_network

  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.16
    depends_on:
      - server
    networks:
      - mc_network
    environment:
      - SECRET_KEY=${PLAYIT_SECRET_KEY}
    command: server:25565

# Custom Network
networks:
  mc_network:
    driver: bridge