services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: spigot-server-1.20.4
    stdin_open: true
    tty: true
    ports:
      - "9584:25565"
    volumes:
      - ./server:/app/server

# Cloudflare Tunnel (Optional - Alternative to Traefik)
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: mc_animae_cloudflared
    restart: unless-stopped
    depends_on:
      - server
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - mc_network
    volumes:
      - ./cloudflared:/etc/cloudflared
    # profiles:
      # - cloudflare
    healthcheck:
      test: ['CMD-SHELL', 'wget --quiet --tries=1 --spider http://server:25565/healthz || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# Custom Network
networks:
  mc_network:
    driver: bridge