# Use the OpenJDK 17 base image
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy your application JAR or other files (adjust as necessary)
COPY . .

# Command to run the application
CMD ["java", "-jar", "spigot-1.20.4.jar"]
